apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-error-page: "https://error.starchild.network/cert-tls-auth"
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: athena-test.com
spec:
  ingressClassName: nginx
  rules:
    - host: athena-test.com
      http:
        paths:
          - backend:
              service:
                name: athena-test-com
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - athena-test.com
      secretName: athena-test-com-tls
