apiVersion: apps/v1
kind: Deployment
metadata:
  name: gurkbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gurkbot
  template:
    metadata:
      labels:
        app: gurkbot
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: bot
          image: ghcr.io/gurkult/gurkbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 400m
              memory: 400Mi
            limits:
              cpu: 5000m
              memory: 500Mi
          envFrom:
            - secretRef:
                name: gurkbot-env
          securityContext:
            readOnlyRootFilesystem: true