apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/cloudflare-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-error-page: "https://error.starchild.network/cert-tls-auth"
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: forum.quiltmc.org
spec:
  ingressClassName: nginx
  rules:
    - host: forum.quiltmc.org
      http:
        paths:
          - backend:
              service:
                name: forum-quiltmc-org
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - forum.quiltmc.org
      secretName: forum-quiltmc-org-tls
