apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: ci
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: default
roleRef:
  kind: Role
  name: ci
  apiGroup: rbac.authorization.k8s.io