apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ci
rules:
- apiGroups:
    - apps
    - batch
  verbs:
    - list
    - get
    - patch
    - create
    - watch
  resources:
    - deployments
    - jobs