apiVersion: v1
kind: Service
metadata:
  name: coredns-local
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.111.42.0
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
