apiVersion: apps/v1
kind: Deployment
metadata:
  name: luna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luna
  template:
    metadata:
      labels:
        app: luna
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: bot
          image: ghcr.io/akarys42/starbot:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
          envFrom:
            - secretRef:
                name: luna-env
            - configMapRef:
                name: luna-config
          securityContext:
            readOnlyRootFilesystem: true