kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-volume
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi