apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
data:
  blackbox.yaml: |
    databases:
      kissland_postgres:
        main_postgres:
          username: {{ POSTGRES_USER }}
          password: {{ POSTGRES_PASSWORD }}
          host: postgres.default.svc.cluster.local
          port: "5432"

    storage:
      s3:
        dawnfm_s3:
          bucket: dawnfm
          endpoint: s3.us-west-004.backblazeb2.com
          aws_access_key_id: {{ AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: {{ AWS_SECRET_ACCESS_KEY }}

    notifiers:
      discord:
        starchild:
          webhook: {{ WEBHOOK }}

    retention_days: 7